// <auto-generated />
using Lollapalooza.Services.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Lollapalooza.Services.Migrations
{
    [DbContext(typeof(LollapaloozaContext))]
    partial class LollapaloozaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lollapalooza.Services.Model.Show", b =>
                {
                    b.Property<int>("ShowId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Band")
                        .IsRequired();

                    b.Property<string>("Day")
                        .IsRequired();

                    b.Property<string>("ImageUrl")
                        .IsRequired();

                    b.Property<string>("Schedule")
                        .IsRequired();

                    b.Property<string>("Stage")
                        .IsRequired();

                    b.HasKey("ShowId");

                    b.ToTable("Show");
                });
#pragma warning restore 612, 618
        }
    }
}
